services:
  - type: web
    name: obsyd
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: HOST
        value: 0.0.0.0
